site_name: Scala Academy
site_url: https://jaceklaskowski.github.io/scala-academy/
site_author: Jacek Laskowski
site_description: 3-month Introduction to Scala and the Ecosystem

repo_name: scala-academy
repo_url: https://github.com/jaceklaskowski/scala-academy
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2022 Jacek Laskowski

theme:
  name: material
  language: en
  icon:
    logo: material/book-open-page-variant
    repo: fontawesome/brands/github
  features:
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    - content.code.annotate
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

plugins:
  - search
  - minify:
      minify_html: true
  - awesome-pages
  - macros
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/
  - tags

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  book:
    title: Scala Academy
    calculator: https://github.com/jaceklaskowski/scala-academy/tree/main/calculator
  scala:
    api: https://www.scala-lang.org/api/2.13.x
    docs: https://docs.scala-lang.org/
    spec: https://www.scala-lang.org/files/archive/spec/2.12
    version: 2.13.8
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jaceklaskowski
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jaceklaskowski
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jaceklaskowski
    - icon: fontawesome/brands/medium
      link: https://jaceklaskowski.medium.com

nav:
  - Home: index.md
  - Scala:
    - scala/index.md
    - Week 1 (Mar 1-4):
      - scala/001.md
      - scala/002.md
      - scala/003.md
      - scala/004.md
    - Week 2 (Mar 7-11):
      - scala/005.md
      - scala/006.md
      - scala/007.md
      - scala/008.md
      - scala/009.md
    - Week 3 (Mar 14-18):
      - scala/010.md
      - scala/011.md
      - scala/012.md
      - scala/013.md
      - scala/014.md
    - Week 4 (Mar 21-25):
      - scala/015.md
      - scala/016.md
      - scala/017.md
      - scala/018.md
      - scala/019.md
    - Week 5 (Mar 28 - April 1):
      - scala/020.md
      - scala/021.md
